#!/usr/bin/env python3
"""
Local server for the GrapesJS editor. Standard library only, no
dependency beyond Python 3.

Serves the static files (the real site + the editor's own assets) and
handles POST /save to write the changes made in the canvas.

Usage:
    python3 editor/server.py [port]      (default: 8767)

Doesn't publish anything on its own: it only writes to disk. `git push`
stays a separate, deliberate step — see scripts/publish.sh.
"""

import http.server
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 8767

# If any of these disappear from the saved HTML, main.js silently stops
# working: the countdown freezes, the RSVP form stops sending, the
# gallery stops opening. A plain string check is enough for a warning —
# no need for a real HTML parser for this purpose.
REQUIRED_IDS = [
    "cd-days", "cd-hours", "cd-minutes", "cd-seconds",
    "countdown", "lightbox", "rsvp-form", "rsvp-note",
]
REQUIRED_CLASSES = ["reveal", "gallery-grid"]
REQUIRED_FIELDS = ["first-name", "last-name", "attending", "guests", "guest-names", "message"]


def find_missing(html):
    missing = []
    for id_ in REQUIRED_IDS:
        if f'id="{id_}"' not in html:
            missing.append(f'id="{id_}"')
    for cls in REQUIRED_CLASSES:
        if not re.search(rf'class="[^"]*\b{re.escape(cls)}\b[^"]*"', html):
            missing.append(f'class="{cls}"')
    for field in REQUIRED_FIELDS:
        if f'name="{field}"' not in html:
            missing.append(f'name="{field}"')
    return missing


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def log_message(self, format_, *args):
        sys.stderr.write(f"[editor] {self.address_string()} — {format_ % args}\n")

    def do_POST(self):
        if self.path != "/save":
            self.send_error(404, "Only /save accepts POST")
            return

        length = int(self.headers.get("Content-Length", 0))
        if length == 0 or length > 10_000_000:
            self._json(400, {"error": "request body missing or too large"})
            return

        try:
            data = json.loads(self.rfile.read(length))
            new_html = data["html"]
            new_css = data["css"]
        except (json.JSONDecodeError, KeyError) as e:
            self._json(400, {"error": f"invalid JSON: {e}"})
            return

        try:
            warnings = self._write(new_html, new_css)
        except Exception as e:
            self._json(500, {"error": str(e)})
            return

        self._json(200, {"ok": True, "warnings": warnings})

    def _write(self, new_html, new_css):
        index_path = ROOT / "index.html"
        current = index_path.read_text(encoding="utf-8")

        if "<body>" not in current or "</body>" not in current:
            raise ValueError("index.html has no <body>/</body>: unexpected structure, writing nothing")

        head, _, rest = current.partition("<body>")
        _, _, tail = rest.rpartition("</body>")

        # GrapesJS's editor.getHtml() includes its own <body> tag (the
        # root component), so it must be stripped before reinserting
        # ours — otherwise you end up with a <body> nested inside another.
        clean_body = new_html.strip()
        clean_body = re.sub(r"^<body[^>]*>", "", clean_body, count=1, flags=re.I)
        clean_body = re.sub(r"</body>\s*$", "", clean_body, count=1, flags=re.I).strip()

        # The <script> tag stays fixed: the editor manages structure and
        # style, not the interactive behavior hand-written in js/main.js.
        new_content = (
            f"{head}<body>\n"
            f"{clean_body}\n"
            f'  <script src="js/main.js"></script>\n'
            f"</body>{tail}"
        )

        index_path.write_text(new_content, encoding="utf-8")

        # Separate layer, never overwrites style.css: if GrapesJS's
        # export didn't carry over some advanced detail (animations,
        # media queries, texture), the site doesn't lose the original.
        edited_path = ROOT / "css" / "edited.css"
        header_comment = (
            "/* Generated by the local editor (GrapesJS) — don't edit by hand.\n"
            "   Layers on top of style.css: the latter stays the base. */\n\n"
        )
        edited_path.write_text(header_comment + new_css, encoding="utf-8")

        return find_missing(clean_body)

    def _json(self, code, body):
        payload = json.dumps(body).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)


if __name__ == "__main__":
    server = http.server.ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    print(f"Editor at http://127.0.0.1:{PORT}/editor/  (project root: {ROOT})")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
